### ISSUE TITLE
Unable to login.

### ISSUE THREAD

**Issue by Senthuran100** [gustavoponce7/spring-login#14]
When I create a new user in the registration page a user is created successfully. But when I login to the login page it redirects to the login page. I have checked the DB and a new user is created in the user table. When observing the network tab there is a 302 in login. Please refer this image for the reference.
![image](https://user-images.githubusercontent.com/32807418/71475987-debd0380-2808-11ea-820a-96019ee13dd4.png)

**Comment by gustavoponce7** [comment]
Please pull the latest changes, the issue has been resolved
