### ISSUE TITLE
Missing License 

### ISSUE THREAD

**Issue by adamantium1987** [gustavoponce7/spring-login#15]
Could you submit a license for this code, so that users know if this code can be used for project, I am very interested in using this code, but wanted to get your permission first.

**Comment by gustavoponce7** [comment]
Done @adamantium1987 , the license has been added (Apache License Version 2.0), feel free to use the code :)

**Comment by adamantium1987** [comment]
Sounds good! Thank you for that , now to go research the license haha , I'm still new to this so not sure what that type of license means.
