### ISSUE TITLE
not able to login

### ISSUE THREAD

**Issue by snkmrjha** [gustavoponce7/spring-login#4]

**Comment by vin0010** [comment]
There was no login post method in the login controller. Let me have a look and fix it.

**Comment by weitiancai** [comment]
I can not login too ...  it says like this:
![image](https://user-images.githubusercontent.com/33573298/57582313-a8d74300-74f5-11e9-8112-da75f72419d8.png)
but i'm sure i write the correct email and password .

**Comment by weitiancai** [comment]
O, i have solved my problem , i should not create database by myself,the application.properties  file 
has one line : spring.datasource.initialization-mode=always
it generate database contents automatically , all i need is give springboot an empty database name;

**Comment by vin0010** [comment]
The actual fix is to change the role query in application.properties which is wrong.

spring.queries.roles-query=select u.email, r.role from users u inner join user_role ur on(u.user_id=ur.user_id) inner join roles r on(ur.role_id=r.role_id) where u.email=?

**Comment by gustavoponce7** [comment]
Please fetch the latest changes, the issue has been resolved
