### ISSUE TITLE
data.sql not gives complete information

### ISSUE THREAD

**Issue by mbagat** [gustavoponce7/spring-login#6]
Hello, gustavoponce7. This code is working. But the data.sql file is not understandable. After import it not gives the necessary table queries. Want the queries for the database structure for tables,views,stored procedures etc to create the database objects in Mysql. Then it would be more helpful. Thank you.

**Comment by endieposts** [comment]
I've raised a pull request which fixes the data.sql file.

Note that if you have the correct entity and component scanning set up then JPA will create the correct entities.

**Comment by gustavoponce7** [comment]
Please fetch the latest changes, the issue has been resolved
